site_name: QSS 20
site_url: https://kengchichang.github.io/QSS20

docs_dir: src

nav:
  - ğŸ¡ Home: index.md
  - ğŸ™‹ Logistics:
    - Course Overview: overview.md
    - Evaluations & Grading: evaluations.md
    - Staff / Office Hours: staff/index.md
    - Tools Overview: tools.md
  - ğŸ’» System Setup:
    - Python and conda: python.md
    - Git and GitHub: git.md
    - VS Code: vscode.md
  - ğŸ“½ï¸ Final Project:
    - Overview: project.md
    - Useful Data Sources: data.md 

theme:
  name: null
  custom_dir: theme
  features:
    - navigation.sections

  static_templates:
    - 404.html

  include_search_page: false
  search_index_only: false

  navigation_depth: 3

  favicon: false

  external_links_before_nav:
    "ğŸ“– Syllabus": https://docs.google.com/document/d/1tWoMG0JoCTQpXIGfXZQwyQxz_gmBQ3p8jzx5zPKqP5g/edit?usp=sharing

  external_links_after_nav:
    "ğŸ’¬ Slack": https://dart-prd-lti-74464.slack.com
    "ğŸ“Š DataCamp": https://www.datacamp.com/groups/shared_links/34a82e1044d5b2a52312ab70aa7b024a74c8c58de48813a10491ac407eefaa02
    "ğŸ’¯ Gradescope": https://www.gradescope.com/courses/1132872

  simple_analytics: false

  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s

markdown_extensions:
  - pymdownx.extra
  - admonition
  - codehilite:
      linenums: true
  - sane_lists
  - smarty:
      smart_angled_quotes: true
  - toc:
      marker: "" # disable, since theme has its own TOC
      permalink: true
      toc_depth: "2-6"
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.escapeall:
      hardbreak: true
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      linenums_style: pymdownx-inline\

# TODO: consider more plugins from https://facelessuser.github.io/pymdown-extensions/
#   keys, caret

plugins:
  - search
  - bootstrap-tables
  - collections: # must load before macros
      collections:
        announcements: {}
        staff: {}
  - macros:
      include_dir: includes
      include_yaml:
        - data/vars.yml
        - data/schedule/lectures.yml
        - data/schedule/exercises.yml
        - data/schedule/projects.yml
  - sass
  - url-validation
  - minify:
      minify_html: true
      minify_js: false
      htmlmin_opts:
        remove_comments: true
